Document: webbrowser
Title: Debian webbrowser Manual
Author: <insert document author here>
Abstract: This manual describes what webbrowser is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webbrowser/webbrowser.sgml.gz

Format: postscript
Files: /usr/share/doc/webbrowser/webbrowser.ps.gz

Format: text
Files: /usr/share/doc/webbrowser/webbrowser.text.gz

Format: HTML
Index: /usr/share/doc/webbrowser/html/index.html
Files: /usr/share/doc/webbrowser/html/*.html
